plugins {
    id 'java-library'
}

java {
    sourceCompatibility = rootProject.ext.javaSourceCompatibility
    targetCompatibility = rootProject.ext.javaTargetCompatibility
}

jar {
    sourceSets.main.resources {
        from('src/main')
        include(['**/*.json'])
    }
    sourceSets.test.resources {
        from('src/test')
        include(['**/*.json'])
    }
}

dependencies {
    implementation 'org.json:json:20260522'
    testImplementation 'junit:junit:4.13.2'
}