plugins {
    id 'java-library'
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

jar {
    sourceSets.main.resources {
        from('src/main')
        include(['**/*.json'])
    }
    sourceSets.test.resources {
        from('src/test')
        include(['**/*.json'])
    }
}

dependencies {
    implementation 'org.json:json:20251224'
    testImplementation 'junit:junit:4.13.2'
}