// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files

        // Exceptions to this rule have been required in the past when the
        // release version of the package com.android.tools.build:gradle
        // (aka the Android Gradle Plugin, or AGP) has brought in dependencies
        // which triggered security vulnerability alerts from GitHub dependabot.

        // AGP is not an application dependency, it adds Android support to
        // the Gradle build environment and needs to be included here
        // for the :android-app package to be buildable.

        // When AGP imported vulnerable dependencies in the past, explicit
        // non-vulnerable versions of the packages named in alerts
        // were imported here, allowing the security alerts to be cleared.

        // As of AGP 8.13.2 there are no alerts on dependencies so
        // the explicit version imports have been removed.

        classpath 'com.android.tools.build:gradle:8.13.2'

    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
    tasks.withType(JavaCompile).tap {
        configureEach {
            options.deprecation = true
        }
    }
}

// For Android apps released via PlayStore, versionCode must
// be a monotonically increasing integer.
// This will be substituted during release candidate builds
// by a script in a release build following the format
// sprintf("%d%02d%02d0%04d",major,minor,patch,build)
// NB Major must have format %d not %02d to avoid interpretation
// as octal.
ext.versionCode=9999
ext.versionName="0.0.0"

tasks.register('warrantyAndCopyrightFiles',Copy) {
    from 'assets'
    include 'copyright_and_warrranty.txt'
}

