// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files

        // We need to include
        // classpath 'com.android.tools.build:gradle:8.13.0'
        // in this section so that the android library and application
        // plugins become available to subproject build.gradle files.
        // The other dependencies listed here are intended to reduce
        // GitHub dependabot noise - they are all non-vulnerable
        // explicit versions of dependencies for which transitive
        // dependencies from c.a.t.b:g:8:13.0 would bring in versions
        // with known vulnerabilities.

        classpath 'org.jsoup:jsoup:1.21.2'
        classpath 'io.netty:netty-common:4.2.7.Final'
        classpath 'io.netty:netty-handler:4.2.7.Final'
        classpath 'io.netty:netty-codec-http:4.2.7.Final'
        classpath 'io.netty:netty-codec-http2:4.2.7.Final'
        classpath 'org.apache.commons:commons-compress:1.28.0'
        classpath "org.apache.commons:commons-lang3:3.19.0"
        classpath "org.apache.commons:commons-collections4:4.5.0"
        classpath "commons-io:commons-io:2.21.0"
        classpath 'com.google.guava:guava:33.5.0-android'
        classpath 'org.jdom:jdom2:2.0.6.1'
        classpath 'com.google.protobuf:protobuf-kotlin:4.33.2'
        classpath 'com.google.protobuf:protobuf-java:4.33.2'

        classpath 'com.android.tools.build:gradle:8.13.1'

    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
    tasks.withType(JavaCompile).tap {
        configureEach {
            options.deprecation = true
        }
    }
}

// For Android apps released via PlayStore, versionCode must
// be a monotonically increasing integer.
// This will be substituted during release candidate builds
// by a script in a release build following the format
// sprintf("%d%02d%02d0%04d",major,minor,patch,build)
// NB Major must have format %d not %02d to avoid interpretation
// as octal.
ext.versionCode=9999
ext.versionName="0.0.0"

tasks.register('warrantyAndCopyrightFiles',Copy) {
    from 'assets'
    include 'copyright_and_warrranty.txt'
}

