// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files

        // Exceptions to this rule will be required in the past when the
        // release version of the package com.android.tools.build:gradle
        // (aka the Android Gradle Plugin, or AGP) has brought in dependencies
        // which triggered security vulnerability alerts from GitHub dependabot.

        // AGP is not an application dependency, it adds Android support to
        // the Gradle build environment and needs to be included here
        // for the :android-app package to be buildable.

        // When AGP attempts to import vulnerable dependencies, explicit
        // non-vulnerable versions of the packages named in alerts
        // should imported here, before AGP.  The import will be resolved
        // by using the non-vulnerable version, allowing the security alerts
        // to be cleared.

        // https://github.com/tim-littlefair/maneline/security/dependabot/3
        // https://github.com/tim-littlefair/maneline/security/dependabot/4
        classpath 'org.apache.commons:commons-compress:1.28.0'

        // https://github.com/tim-littlefair/maneline/security/dependabot/14
        classpath 'org.jdom:jdom2:2.0.6.1'

        // https://github.com/tim-littlefair/maneline/security/dependabot/15
        classpath 'io.netty:netty-codec-http:4.2.10.Final'

        // https://github.com/tim-littlefair/maneline/security/dependabot/16
        classpath 'org.bitbucket.b_c:jose4j:0.9.6'

        // https://github.com/tim-littlefair/maneline/security/dependabot/18
        classpath 'org.apache.httpcomponents:httpclient:4.5.14'

        // https://github.com/tim-littlefair/maneline/security/dependabot/19
        classpath 'org.apache.commons:commons-lang3:3.20.0'

        classpath 'com.android.tools.build:gradle:9.0.0'

    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
    tasks.withType(JavaCompile).tap {
        configureEach {
            options.deprecation = true
        }
    }
}

// For Android apps released via PlayStore, versionCode must
// be a monotonically increasing integer.
// This will be substituted during release candidate builds
// by a script in a release build following the format
// sprintf("%d%02d%02d0%04d",major,minor,patch,build)
// NB Major must have format %d not %02d to avoid interpretation
// as octal.
ext.versionCode=9999
ext.versionName="0.0.0"

tasks.register('warrantyAndCopyrightFiles',Copy) {
    from 'assets'
    include 'copyright_and_warrranty.txt'
}

