plugins {
    id 'java'
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

jar {
    manifest {
        attributes "Main-Class" : 'net.heretical_camelid.maneline.desktop_app.CommandLineInterface'
        attributes "Implementation-Version" : "$rootProject.ext.versionName"
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    from('..') {
        include "LICENSE"
        include "assets/copyright_and_warranty.txt"
        include "assets/warranty_disclaimer.txt"
        include "assets/dtcli_usage.txt"
        include "assets/dtcli_interactive_help.txt"
        include "assets/50-fhau.rules"
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    dependsOn(':maneline-lib:jar')
}

base {
    archivesName = "maneline-cli-$rootProject.ext.versionName"
}

dependencies {
    implementation project(':maneline-lib') 
    implementation 'ch.qos.logback:logback-classic:1.5.27'
    implementation 'net.logstash.logback:logstash-logback-encoder:9.0'
    implementation 'net.java.dev.jna:jna:5.18.1'
    implementation 'org.hid4java:hid4java:0.8.0'
    implementation 'com.google.code.gson:gson:2.13.2'

    // implementation 'org.sputnikdev.bluetooth-manager-tinyb:1.3.3'
    // implementation 'org.sputnikdev.bluetooth-manager:1.5.3'
    // implementation 'org.sputnikdev:org.eclipse.smarthome.binding.bluetooth.transport.tinyb:1.1.3'
    // implementation 'org.sputnikdev:bluetooth-gatt-parser:1.9.4'
    // implementation 'org.sputnikdev:bluetooth-utils:1.14'

}
