/* This file was generated by code in the following project:
 * https://github.com/tim-littlefair/moonshine-wrangler
 * Manual edits can be used for experimentation but should 
 * not be checked in
 */

package net.heretical_camelid.maneline.lib.presets;

import static net.heretical_camelid.maneline.lib.generated.FUSE_Constants._MODULE_NAMES_AND_TYPES;
import static net.heretical_camelid.maneline.lib.generated.FUSE_Constants._MODULE_PARAMS;

import net.heretical_camelid.maneline.lib.utilities.Pair;

import java.io.FileInputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;


public class FUSE_Classic_Preset extends PresetBase {
    final static private int AMP_POS = 4;
    final static private int MAX_MODULES = 9;
    public static FUSE_Classic_Preset create(byte[] presetBytes) {
        final String presetName;
        DspModule modules[] = new DspModule[MAX_MODULES];
        if (presetBytes.length == 64 * 8) {
            presetName = (
                new String(presetBytes, 16, 48, StandardCharsets.UTF_8)
                    .replace("\u0000", "")
            );
            bytesToAmp(
                Arrays.copyOfRange(presetBytes, 64 * 1, 64 * 2),
                Arrays.copyOfRange(presetBytes, 64 * 6, 64 * 7),
                modules
            );
            for (int i = 2; i < 6; ++i) {
                bytesToEffect(
                    Arrays.copyOfRange(presetBytes, i * 64, (i + 1) * 64),
                    modules
                );
            }
        } else {
            throw new UnsupportedOperationException(String.format(
                "FUSE preset cannot be created for buffer of %d bytes",
                presetBytes.length
            ));
        }
        SignalChain signalChain = SignalChain.create(modules);
        return new FUSE_Classic_Preset(presetName, signalChain, presetBytes);
    }

    private FUSE_Classic_Preset(String presetName, SignalChain signalChain, byte[] presetBytes) {
        super(presetName, signalChain, CompanionAppName_e.FUSE_CLASSIC_USB, presetBytes);
    }

    private static String paramCanonicalName(String paramFuseName) {
        return paramFuseName.replaceAll("\\W","");
    }

    private static Object paramCanonicalValue(int fuseValueU8, int fuseParamType) {
        final Object canonicalValue;
        switch(fuseParamType) {
            // Generic, with exact mapping for 0.5:
            // 1 -> 0.0, , 128-> 0.5, 255 -> 1.0
            case 12:
            case 13:
                canonicalValue = (-1.0F+fuseValueU8)/255.0F;
                break;

            default:
                canonicalValue = fuseValueU8;
        }
        return canonicalValue;
    }
    /**
     * This function analyzes a sequence of bytes, 
     * generates a DspModule/JSONObject and returns 
     * the audio
     */
    static void bytesToAmp(byte[] ampBytes1, byte[] ampBytes2, DspModule[] modules) {
        assert ampBytes1[2]==5;
        int ampId = (0xFF&ampBytes1[16]) + (0x100*ampBytes1[17]);
        Pair<String,String> moduleTypeAndName = _MODULE_NAMES_AND_TYPES.get(ampId);
        if(moduleTypeAndName!=null) {
            assert moduleTypeAndName.first.equals("A");
            List<DspParameterWithDetails> parameters = getDspParameters(ampBytes1, ampId);
            DspModule ampModule = new DspModule(
                moduleTypeAndName.second, "amp",
                parameters
            );
            modules[AMP_POS] = ampModule;
        } else {
            modules[AMP_POS] = null;
        }
    }

    private static List<DspParameterWithDetails> getDspParameters(byte[] ampBytes1, int ampId) {
        List<DspParameterWithDetails> parameters = new ArrayList<>();
        for(int i=0; i<22; ++i) {
            Pair<String, Integer> paramMetadata = _MODULE_PARAMS.get(
                new Pair<>(ampId,i)
            );
            if(paramMetadata==null) {
                continue;
            }
            Map<String, Object> fuseDetails = new LinkedHashMap<>();
            String fuseParamName = paramMetadata.first;
            int fuseParamType = paramMetadata.second;
            int paramValueU8 = 0xFF& ampBytes1[32+i];
            fuseDetails.put("_fuseParamName", fuseParamName);
            fuseDetails.put("_fuseParamType", fuseParamType);
            fuseDetails.put("_fuseValueU8", paramValueU8);
            parameters.add(new DspParameterWithDetails(
                paramCanonicalName(fuseParamName),
                paramCanonicalValue(paramValueU8, fuseParamType),
                fuseDetails
            ));
        }
        return parameters;
    }


    static void bytesToEffect(byte[] effectBytes, DspModule[] modules) {
        assert effectBytes[2]>=6&&effectBytes[2]<=9;
        int effectId = (0xFF&effectBytes[16]) + (0x100*effectBytes[17]);
        int signalChainPos= (0xFF&effectBytes[18]);
        if(signalChainPos>=AMP_POS) {
            signalChainPos+=1;
        }
        Pair<String,String> moduleTypeAndName = _MODULE_NAMES_AND_TYPES.get(effectId);
        if(moduleTypeAndName!=null) {
            assert moduleTypeAndName.first.equals("A")==false;
            List<DspParameterWithDetails> parameters = getDspParameters(effectBytes, effectId);
            DspModule effectModule = new DspModule(
                moduleTypeAndName.second,
                jsonModuleType(moduleTypeAndName.first),
                parameters
            );

            modules[signalChainPos] = effectModule;

        } else {
            modules[signalChainPos] = null;
        }
    }


    static String jsonModuleType(String moduleTypeString) {
        switch(moduleTypeString.charAt(0)) {
            case 'S': return "stomp";
            case 'M': return "mod";
            case 'A': return "amp";
            case 'D': return "delay";
            case 'R': return "reverb";
            default: return "?" + moduleTypeString + "?";
        }
    }

    static public void main(String[] args) {
        final int RAW_PRESET_BUFFER_LENGTH=512;
        try {
            FileInputStream fis = new FileInputStream(args[0]);
            byte[] rawPresetBuffer = new byte[RAW_PRESET_BUFFER_LENGTH];
            int bytesRead = fis.read(rawPresetBuffer);
            assert bytesRead==RAW_PRESET_BUFFER_LENGTH;
            FUSE_Classic_Preset fcp = FUSE_Classic_Preset.create(rawPresetBuffer);
            System.out.println(fcp.displayName());
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

/*
        PresetBase testPreset1 = (PresetBase) (new PresetBase().put("displayName","testPreset1"));
        System.out.println(testPreset1.toString(4));
        JSONArray nodesArray1 = testPreset1.m_audioGraph_nodes;
        assert nodesArray1 != null;
        assert nodesArray1.length()==5;
        for(int i=0; i<nodesArray1.length(); ++i) {
         assert nodesArray1.isNull(i);
        }

        PresetBase testPreset2 = (PresetBase) (new PresetBase().put("displayName","testPreset2"));
        testPreset2.addAudioGraphNode(
         "Deluxe65", "amp",
         "{}",
         2
        );
        System.out.println(testPreset2.toString(4));
        assert testPreset2.m_audioGraph_nodes.length() == 5;
        String ampFenderId = (String) getSubObject(
         testPreset2,
         List.of("audioGraph","nodes", 2, "FenderId")
        );
        assert ampFenderId.equals("Deluxe65");

        PresetBase testPreset3 = create(testPreset2.exportPresetRecord());
        testPreset3.addAudioGraphNode("Passthru","stomp",null,0);
        testPreset3.addAudioGraphNode("SineTremolo","mod",null,1);
        testPreset3.addAudioGraphNode("Passthru","delay",null,3);
        testPreset3.addAudioGraphNode("Passthru","reverb",null,4);
        System.out.println(testPreset3.toString(4));
        // The hash below needs to be maintained manually
        PresetRecord pr3 = testPreset3.exportPresetRecord();
        String expectedHash = "7b19-14e2";
        assert pr3.audioHash().equals(expectedHash): String.format(
         "audioHash mismatch: expected=%s actual=%s",
         expectedHash, pr3.audioHash()
        );
*/
        System.exit(0);
    }


}

