/* This file was generated by code in the following project:
 * https://github.com/tim-littlefair/moonshine-wrangler
 * Manual edits can be used for experimentation but should 
 * not be checked in
 */

package net.heretical_camelid.maneline.lib.presets;

import static net.heretical_camelid.maneline.lib.generated.FUSE_Constants._MODULE_NAMES_AND_TYPES;
import static net.heretical_camelid.maneline.lib.generated.FUSE_Constants._MODULE_PARAMS;

import net.heretical_camelid.maneline.lib.utilities.ByteArrayTranslator;
import net.heretical_camelid.maneline.lib.utilities.Pair;

import org.json.JSONArray;
import org.json.JSONObject;

import java.io.FileInputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;


public class FUSE_Classic_Preset extends PresetBase {
    final static private int AMP_POS = 4;
    final static private int MAX_MODULES = 9;
    private JSONObject m_fuseJO;
    static private JSONArray s_conversionLog = null;

    public static FUSE_Classic_Preset create(byte[] presetBytes) {
        assert s_conversionLog == null;
        s_conversionLog = new JSONArray();
        final String presetName;
        DspModule modules[] = new DspModule[MAX_MODULES];
        assert presetBytes.length == 64 * 8;

        presetName = (
            new String(presetBytes, 16, 48, StandardCharsets.UTF_8)
                .replace("\u0000", "")
        );
        bytesToAmp(
            Arrays.copyOfRange(presetBytes, 64 * 1, 64 * 2),
            Arrays.copyOfRange(presetBytes, 64 * 6, 64 * 7),
            modules
        );
        for (int i = 2; i < 6; ++i) {
            bytesToEffect(
                Arrays.copyOfRange(presetBytes, i * 64, (i + 1) * 64),
                modules
            );
        }

        SignalChain signalChain = SignalChain.create(modules);
        FUSE_Classic_Preset newInstance = new FUSE_Classic_Preset(
            presetName, signalChain, presetBytes
        );
        s_conversionLog = null;
        return newInstance;
    }

    private FUSE_Classic_Preset(String presetName, SignalChain signalChain, byte[] presetBytes) {
        super(presetName, signalChain, CompanionAppName_e.FUSE_CLASSIC_USB, presetBytes);
        m_fuseJO = new JSONObject();
        JSONArray rawBytesFrames = new JSONArray();
        for(int i=0; i<8; ++i) {
            rawBytesFrames.put(hexForRange(presetBytes,64*i,64*(i+1)));
        }
        m_fuseJO.put("rawBytes",rawBytesFrames);
        m_fuseJO.put("conversionLog", s_conversionLog);
    }

    private static String canonicalParamName(String fuseParamName, Map<String, Object> fuseDetails) {
        String retval = fuseParamName.replaceAll("\\W","");
        retval = retval.substring(0,1).toLowerCase()+retval.substring(1);
        if(retval.equals(fuseParamName)==false) {
            fuseDetails.put("_fuseParamName", fuseParamName);
        }
        return retval;
    }

    private static Object paramCanonicalValue(int fuseValueU8, int fuseParamType, Map<String, Object> fuseDetails) {
        final Object canonicalValue;
        switch(fuseParamType) {
            // Generic, with exact mapping for 0.5:
            // 1 -> 0.0, , 128-> 0.5, 255 -> 1.0
            case 1:
            case 12:
            case 13:
                canonicalValue = (fuseValueU8-1.0F)/254.0F;
                // record value before canonical format rounds to 3 decimal places
                fuseDetails.put("_fuseRawFloatValue", canonicalValue);
                // The physical knobs on the MustangIv2 model, and some of the skeuomorphic UIs
                // in FenderFUSE for some amps/effects require settings to be entered using a knob
                // with 9 ticks numbered from 1 to 10.
                // The LCD UI on the Mustang LT40S also requires selection of values on a 1.0 to
                // 10.0 range, so it is convenient to have access to a rendering of how a given
                // raw value is represented on that scale.
                Float nineTickPos = 1.0F + ((Float) canonicalValue*9);
                fuseDetails.put(
                    "_nineTickKnobPos", Float.valueOf(String.format("%.01f",nineTickPos))
                );
                break;

            case 144:
                // Noise gate state
                canonicalValue = getEnumerationValue(
                    new String[]{
                        "off", "low", "medium", "high", "extreme"
                    },
                    fuseValueU8,fuseDetails,17
                );
                break;

            default:
                canonicalValue = fuseValueU8;
        }
        return canonicalValue;
    }

    private static Object getEnumerationValue(String[] enumValueStrings, int fuseValueU8, Map<String, Object> fuseDetails, int nullIndicatorIndex) {
        if (fuseValueU8 == nullIndicatorIndex) {
            return null;
        } else if (fuseValueU8 >= enumValueStrings.length) {
            fuseDetails.put("_fuseException", "enum value out of range");
            return null;
        } else {
            return enumValueStrings[fuseValueU8];
        }
    }

    /**
     * Parameters of the amp's DspModule object are in frames 1 and 6
     */
    static void bytesToAmp(byte[] ampBytes1, byte[] ampBytes6, DspModule[] modules) {
        assert ampBytes1[2]==5;
        int ampId = (0xFF&ampBytes1[16]) + (0x100*ampBytes1[17]);
        Pair<String,String> moduleTypeAndName = _MODULE_NAMES_AND_TYPES.get(ampId);
        if(moduleTypeAndName!=null) {
            assert moduleTypeAndName.first.equals("A");
            s_conversionLog.put(String.format(
                "Processing amp with id=%d name=%s",
                ampId, moduleTypeAndName.second
            ));
            s_conversionLog.put("ampFrame1: " + hexForRange(ampBytes1,0,64));
            s_conversionLog.put("ampFrame6: " + hexForRange(ampBytes6,0,64));
            s_conversionLog.put(hexForRange(ampBytes6,0,64));
            List<DspParameterWithDetails> parameters = getDspParameters(ampBytes1, ampId);
            DspModule ampModule = new DspModule(
                moduleTypeAndName.second, "amp",
                parameters
            );
            s_conversionLog.put("dspModule: " + ampModule.toString());
            modules[AMP_POS] = ampModule;
        } else {
            modules[AMP_POS] = null;
        }
    }

    private static List<DspParameterWithDetails> getDspParameters(byte[] ampBytes1, int ampId) {
        List<DspParameterWithDetails> parameters = new ArrayList<>();
        for(int i=0; i<22; ++i) {
            Pair<String, Integer> paramMetadata = _MODULE_PARAMS.get(
                new Pair<>(ampId,i)
            );
            if(paramMetadata==null) {
                continue;
            }
            Map<String, Object> fuseDetails = new LinkedHashMap<>();
            String fuseName = paramMetadata.first;
            String canonicalName = canonicalParamName(fuseName, fuseDetails);
            int fuseParamType = paramMetadata.second;
            int paramValueU8 = 0xFF&ampBytes1[32+i];
            int paramValueU16single = paramValueU8 << 8;
            int paramValueU16double = paramValueU8 + paramValueU16single;
            fuseDetails.put("_fuseParamIndex", i);
            fuseDetails.put("_fuseParamType", fuseParamType);
            fuseDetails.put("_fuseValueU8", paramValueU8);
            if(i<12) {
                // The XML-based .fuse file format contains 16 bit parameter
                // values for parameters 0-11.
                // Mostly these are equal to the 8-bit on the wire values
                // left-shifted 8 bits but sometimes the 8-bit value
                // is repeated in the low order byte.
                // It is convenient to have these to values available to compare
                fuseDetails.put("_fuseValueU16a", paramValueU16single);
                fuseDetails.put("_fuseValueU16b", paramValueU16double);
            }
            parameters.add(new DspParameterWithDetails(
                canonicalName,
                paramCanonicalValue(paramValueU8, fuseParamType, fuseDetails),
                fuseDetails
            ));
        }
        return parameters;
    }


    static void bytesToEffect(byte[] effectBytes, DspModule[] modules) {
        assert effectBytes[2]>=6&&effectBytes[2]<=9;
        int effectId = (0xFF&effectBytes[16]) + (0x100*effectBytes[17]);
        int signalChainPos= (0xFF&effectBytes[18]);
        if(signalChainPos>=AMP_POS) {
            signalChainPos+=1;
        }
        Pair<String,String> moduleTypeAndName = _MODULE_NAMES_AND_TYPES.get(effectId);
        if(moduleTypeAndName!=null) {
            assert moduleTypeAndName.first.equals("A")==false;
            s_conversionLog.put(String.format(
                "Processing effect with id=%d type=%s name=%s",
                effectId, moduleTypeAndName.first, moduleTypeAndName.second
            ));
            s_conversionLog.put("effectFrameX: " + hexForRange(effectBytes,0,64));
            List<DspParameterWithDetails> parameters = getDspParameters(effectBytes, effectId);
            DspModule effectModule = new DspModule(
                moduleTypeAndName.second,
                jsonModuleType(moduleTypeAndName.first),
                parameters
            );
            s_conversionLog.put("dspModule: " + effectModule.toString());
            modules[signalChainPos] = effectModule;

        } else {
            modules[signalChainPos] = null;
        }
    }

    @Override
    public String modelSpecificJson() {
        return m_fuseJO.toString();
    }

    static String jsonModuleType(String moduleTypeString) {
        switch(moduleTypeString.charAt(0)) {
            case 'S': return "stomp";
            case 'M': return "mod";
            case 'A': return "amp";
            case 'D': return "delay";
            case 'R': return "reverb";
            default: return "?" + moduleTypeString + "?";
        }
    }

    static public void main(String[] args) {
        final int RAW_PRESET_BUFFER_LENGTH=512;
        try {
            final String rawPresetFilename;
            if(args.length==0) {
                rawPresetFilename = "./_work/pigs/Pigs_Can_Fly-FUSE_CLASSIC_USB.raw";
            } else {
                rawPresetFilename = args[0];
            }
            FileInputStream fis = new FileInputStream(rawPresetFilename);
            byte[] rawPresetBuffer = new byte[RAW_PRESET_BUFFER_LENGTH];
            int bytesRead = fis.read(rawPresetBuffer);
            assert bytesRead==RAW_PRESET_BUFFER_LENGTH;
            FUSE_Classic_Preset fcp = FUSE_Classic_Preset.create(rawPresetBuffer);
            String presetDisplayName = fcp.displayName();

            System.out.println("presetDisplayName: " + presetDisplayName);
            for(DspModule m: fcp.signalChain()) {
                System.out.println(
                    "    " +
                    m.toString(0,false).replaceAll("\\^","    ")
                );
            }

            if(args.length==0) {
                // Default input file (hardcoded) => we can assert on expected values
            } else {
                // Input file supplied by users, we can only dump various outputs for manual checking
                if(args.length==2) {
                    // If an extra parameter is supplied it is the index of a single module
                    // to be dumped with details
                    int moduleIndex = Integer.valueOf(args[1]);
                    System.out.println(
                        fcp.m_signalChain.get(moduleIndex).toString(4,true)
                    );
                } else {
                    // If no extra parameter is supplied, all modules are dumped, without details
                    assert args.length==1;
                    for(DspModule m: fcp.m_signalChain) {
                        System.out.println(m.toString(4, false));
                    }
                }
            }
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        System.exit(0);
    }

    static String hexForRange(byte[] byteArray, int startIndex, int endIndex) {
        return ByteArrayTranslator.bytesToHex(Arrays.copyOfRange(byteArray, startIndex, endIndex));
    }

}

