# Root logger
log4j.rootLogger=INFO, CONSOLE, SESSION_LOGGER, TRANSACTION_LOGGER

# Direct to console
log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
log4j.appender.CONSOLE.Target=System.out
log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
log4j.appender.CONSOLE.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

# Direct to a file
log4j.appender.SESSION_LOGGER=net.heretical_camelid.maneline.desktop_app.WebModeLogAppender
log4j.appender.SESSION_LOGGER.Name=SESSION_APPENDER
log4j.appender.SESSION_LOGGER.File=session.log
log4j.appender.SESSION_LOGGER.MaxFileSize=5MB
log4j.appender.SESSION_LOGGER.MaxBackupIndex=2
log4j.appender.SESSION_LOGGER.layout=org.apache.log4j.PatternLayout
log4j.appender.SESSION_LOGGER.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

#log4j.appender.TRANSACTION_LOGGER=org.apache.log4j.RollingFileAppender
#log4j.appender.TRANSACTION_LOGGER.File=txn.log
#log4j.appender.TRANSACTION_LOGGER.MaxFileSize=5MB
#log4j.appender.TRANSACTION_LOGGER.MaxBackupIndex=2
#log4j.appender.TRANSACTION_LOGGER.layout=org.apache.log4j.PatternLayout
#log4j.appender.TRANSACTION_LOGGER.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
