version: "0.2.0-rpi-balena"

services:
  fhau-device-cli:
    build: .

  browser:
    image: bh.cr/balenalabs/browser-aarch64
    privileged: true
    ports:
        - '5011' # management API (optional)
        - '35173' # Chromium debugging port (optional)
    environment: 
        EXTRA_FLAGS: --no-memcheck
        SHOW_CURSOR: 1
        KIOSK: 1
        LAUNCH_URL: https://github.com/tim-littlefair/feral-horse-amp-utils/blob/main/README.md
    # volumes:
    #  - 'settings:/data' # Only required if using PERSISTENT flag (see below)