# docker-compose.yml

# The design for the Balena image this file will render
# is that it should contain the following two service containers:
# + tl-maneline-web
#   This container will contain the maneline CLI binary, and also a
#   minimal web server which will serve a GUI reflecting the 
#   CLI application state and servicing requests to send messages
#   to the attached Mustang amp (which will be relayed to CLI 
#   commands to the application)
# + balenalabs-browser
#   This is a kiosk browser provided as an example by balena.io.
#   The intent of this service is that that the web GUI
#   will be presented on the HDMI screen of the balena device.

version: "2"

volumes:
  opt-maneline:

services:
  balenalabs-browser:
    volumes:
      - opt-maneline:/opt/maneline
    image: bh.cr/gh_tim_littlefair/tl-browser-aarch64/fca86032af0984f74fffcce1d2f7a152
    privileged: true
    network_mode: host
    devices:
      - /dev/fb0
    ports:
      - '5011' # management API (optional)
      - '35173' # Chromium debugging port (optional)
    environment: 
      - UDEV=1
      - SHOW_CURSOR=1
      - KIOSK=1
      - PERSISTENT=1
      - LAUNCH_URL=http://127.0.0.1:8080/web_ui/index.html
      - ENABLE_GPU=1
      - LAUNCH_URL=file:///opt/maneline/web_ui/_static/maneline-logo-512x512.png

  maneline-web:
    depends_on:
      - balenalabs-browser
    volumes:
      - opt-maneline:/opt/maneline
    build: .
    network_mode: host
    privileged: true
    ports:
      - 8080
    environment:
      - UDEV=1
      - LOCAL_BROWSER=1
      - PERSISTENT=1
    devices:
      - /dev:/dev
    cap_add:
      - SYS_RAWIO
