# docker-compose.yml

# The design for the Balena image this file will render
# is that it should contain the following two service containers:
# + tl-maneline-web
#   This container will contain the maneline CLI binary, and also a
#   minimal web server which will serve a GUI reflecting the 
#   CLI application state and servicing requests to send messages
#   to the attached Mustang amp (which will be relayed to CLI 
#   commands to the application)
# + balenalabs-browser
#   This is a kiosk browser provided as an example by balena.io.
#   The intent of this service is that that the web GUI
#   will be presented on the HDMI screen of the balena device.

version: "2"

volumes:
  var-run-maneline:

services:
  balenalabs-browser:
    volumes:
      - var-run-maneline:/var/run/maneline
    # The browser image we use is built from this tag:
    # https://github.com/tim-littlefair/tl-balena-browser/releases/tag/2.12.0%2Bpatch.tl.250909
    # This build consists of balena's first party 2.11.0 release from
    # https://github.com/balena-io-experimental/browser/releases/tag/v2.11.0
    # with two PR's by Tim Littlefair integrated.
    # The PRs are:
    # PR190: Add support for file: and data: URIs in parameter LAUNCH_URL
    # PR191: Add --no-memcheck to chromium invocations to allow block to work on RPi0w2
    image: bh.cr/gh_tim_littlefair/tl-browser-aarch64/ad82b88e50e713d303e29f72e8bdbc38
    privileged: true
    network_mode: host
    devices:
      - /dev/fb0
    ports:
      - '5011' # management API (optional)
      - '35173' # Chromium debugging port (optional)
    environment: 
      - ENABLE_GPU=1
      - UDEV=1
      - SHOW_CURSOR=1
      - KIOSK=1
      - LAUNCH_URL=file:///var/run/maneline/web_ui/_static/maneline-icon-512x512.png

  maneline-web:
    volumes:
      - var-run-maneline:/var/run/maneline
    build: .
    network_mode: host
    privileged: true
    ports:
      - 8080
    environment:
      - UDEV=1
      - LOCAL_BROWSER=1
    devices:
      - /dev:/dev
    cap_add:
      - SYS_RAWIO


