version: "2"

services:
  tl-fhau-cli:
    build: .
    devices:
      - "/dev/hidraw0"
    cap_add:
      - SYS_RAWIO

  balenalabs-browser:
    image: bh.cr/balenalabs/browser-aarch64
    privileged: true
    ports:
      - '5011' # management API (optional)
      - '35173' # Chromium debugging port (optional)
    environment: 
      EXTRA_FLAGS: --no-memcheck
      SHOW_CURSOR: 1
      KIOSK: 1
      LAUNCH_URL: https://heretical-camelid.net
      PERSISTENT: 0
    #volumes:
    #  - 'settings:/data'
